// Generic upload-pipeline primitives shared by both the wiki-page uploader
// and the file uploader. Each entity (upgrades, gears, …) supplies a config
// that plugs into these functions so the per-entity scripts collapse to thin
// wrappers.

import path from 'node:path';

// Min interval between request *starts* (for any single rate-limited gate).
// The MediaWiki API permits more, but 1/s is courteous and stable.
export const DEFAULT_RATE_LIMIT_MS = 1000;
export const DEFAULT_CONCURRENCY = 1;

// Slot-based rate limiter: nextSlotAt advances by rateMs whether or not the
// previous request finished. Avoids "double-paying" for slow requests.
export function createRateLimiter(rateMs: number = DEFAULT_RATE_LIMIT_MS): () => Promise<void> {
	let nextSlotAt = 0;
	return async () => {
		const now = Date.now();
		const slot = Math.max(now, nextSlotAt);
		nextSlotAt = slot + rateMs;
		const wait = slot - now;
		if (wait > 0) await new Promise((r) => setTimeout(r, wait));
	};
}

export async function runWithConcurrency<T>(
	items: T[],
	concurrency: number,
	worker: (item: T, index: number) => Promise<void>
): Promise<void> {
	let next = 0;
	const runners = Array.from({ length: Math.min(concurrency, items.length) }, async () => {
		while (true) {
			const i = next++;
			if (i >= items.length) return;
			await worker(items[i], i);
		}
	});
	await Promise.all(runners);
}

// Per-entity classifier knobs for the host-page uploader. Each entity supplies
// the placeholder phrases its skeleton template emits, the section headings
// that are curator-territory, and so on.
export interface EntityClassifierConfig {
	placeholderPhrases: string[];
	cannedAcquisitionPhrases: Set<string>; // lowercased phrases
	curatorOnlySections: Set<string>; // lowercased headings
	autoGenSections: Set<string>; // lowercased headings (regenerated by bot)
	infoboxStripPattern: RegExp; // matches the entity's infobox template invocation
	// Extra wikitext patterns the bot itself emits inside otherwise
	// curator-owned sections (images, layout templates, etc.). Stripped
	// before evaluating whether a section has curator content. Optional —
	// entities that don't emit anything beyond placeholders can omit this.
	botEmittedPatterns?: RegExp[];
}

// Per-entity upload registration. The wiki / file uploader dispatches on
// `--entity=NAME` to pick one of these.
export interface EntityFileSpec<T> {
	kind: string; // 'icon' | 'pattern' | …
	sourceDirKind: 'icons' | 'svgs'; // which generated-* dir to read from
	suffix: string; // filename ending, used when scanning the source dir
	targetFilename: (item: T) => string; // wiki File: name (no "File:" prefix)
	localFilename: (item: T) => string; // local filename in the generated dir
	description: (item: T) => string; // wiki text for the File: page body
}

export interface EntityUploadConfig<T> {
	name: string; // 'upgrades' | 'gears'
	loadItems: () => T[];
	pageTitle: (item: T) => string;
	safeFilename: (item: T) => string; // matches *.source.wiki / *.skeleton.wiki basenames
	infoboxDescription: (item: T) => string; // for classifier preamble fuzzy-match
	identLabel: (item: T) => string; // for log lines
	classifier: EntityClassifierConfig;
	fileTypes: EntityFileSpec<T>[];
}

// Resolve an entity name to its upload config. Backed by the entity
// registry (`./entity-registry.ts`) — each entity ships a single
// `defineEntity({...})` block in its module that the registry exposes.
export async function resolveEntity(name: string): Promise<EntityUploadConfig<unknown>> {
	const { getEntity } = await import('./entity-registry');
	return (await getEntity(name)).uploadConfig;
}

export { knownEntities } from './entity-registry';

// Helper: pretty-print a relative path for log output.
export function relPath(p: string): string {
	return path.relative(process.cwd(), p);
}
