/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A playable character. Extends Gear with character-specific metadata (branding, voice lines, default loadout).
 */
export type CharacterEntry = Gear & {
  /**
   * Stable roster index.
   */
  Index?: number;
  IsPlayable?: boolean;
  /**
   * In-fiction employee ID shown on UI.
   */
  EmployeeID?: string;
  /**
   * Primary UI color as Unity RGBA(r, g, b, a) string.
   */
  UIColor?: string;
  /**
   * Text color for UI labels.
   */
  TextColor?: string;
  /**
   * Particle color (HDR — may exceed 1.0 per channel).
   */
  ParticleColor?: string;
  /**
   * Hex string (no #) matching UIColor — used in rich-text tags.
   */
  PrimaryColorTag?: string;
  /**
   * Hex string (no #) matching TextColor.
   */
  TextColorTag?: string;
  /**
   * C# class name of the character's default PlayerUpgrade (movement ability, e.g. AirDashUpgrade for Glider).
   */
  DefaultUpgradeType?: string;
  /**
   * C# class name of the character's default SkinUpgrade.
   */
  DefaultSkinType?: string;
  /**
   * Voice-line catalog (battle and contextual lines).
   */
  Quips?: Quip[];
  /**
   * Default emote wheel entries.
   */
  DefaultEmotes?: Quip[];
  /**
   * Per-character skill tree nodes — extracted by walking each Character's `SkillTree` MonoBehaviour and reading its `SkillTreeUpgradeUI` children. Each node has a `Layer` (tier — 0 = root, growing outward), grid coordinates `CoordX`/`CoordY` for the tree visual, an `Upgrade` it grants when purchased, and an optional `MustBeUnlockedFirst` prerequisite chain. Total nodes match the count of `Upgrade.CollectionSource == "UpgradeTree"` (126).
   */
  SkillTree?: SkillTreeNode[];
};

/**
 * JSON Schema for the dump produced by the MycopunkDumper BepInEx plugin for the Unity game Mycopunk. The dump is a static catalog of every upgrade, gear, character, resource, and directive defined in the game, extracted by walking publicized game state at runtime and serializing it via Newtonsoft.Json (with a JsonUtility shim for Unity-native types). See SCHEMA_CHANGES.md for the migration history from the legacy upgrades.json shape.
 */
export interface MycopunkDumperDataJson {
  /**
   * Game version metadata captured at dump time. Sourced from Global.Version (Application.version, the value shown on the start menu) and Global.BuildID (Steam build ID via Online.GetBuildID).
   */
  gameVersion: {
    /**
     * Application.version (semantic-ish, e.g. "1.2.0").
     */
    Version: string;
    /**
     * Steam build ID as returned by the platform layer; may be "0" or empty when not running under Steam.
     */
    BuildID?: string;
    /**
     * ISO-8601 UTC timestamp when this dump was produced (yyyy-MM-ddTHH:mm:ssZ).
     */
    DumpedAt?: string;
  };
  /**
   * Catalog of every upgrade in the game keyed by stringified UpgradeID. Vanilla upgrades use the bare integer (e.g. "99770"); modded upgrades use "<Mod>:<ID>". Negative IDs occur for some game-defined upgrades and are valid.
   */
  upgrades: {
    [k: string]: Upgrade;
  };
  /**
   * Catalog of non-character upgradables (weapons, grenades, utility, vehicles, etc.) keyed by GearInfo.APIName (e.g. "smg", "accelerator", "wrench").
   */
  gears: {
    [k: string]: Gear;
  };
  /**
   * Catalog of playable characters keyed by GearInfo.APIName ("wrangler", "bruiser", "scrapper", "glider").
   */
  characters: {
    [k: string]: CharacterEntry;
  };
  /**
   * Game-economy catalog from PlayerResource ScriptableObjects, keyed by PlayerResource.ID (e.g. "saxonite", "scrip", "beezia").
   */
  resources: {
    [k: string]: Resource;
  };
  /**
   * Mission-modifier directive catalog from DirectiveData ScriptableObjects, keyed by stringified integer ID.
   */
  directives: {
    [k: string]: Directive;
  };
  /**
   * Mission catalog from Global.Instance.Missions, keyed by Mission.ID (a string identifier like "sat_salvage", "ouroboros").
   */
  missions: {
    [k: string]: MissionEntry;
  };
  /**
   * Objective-prefab catalog (ObjectiveBase subclasses). Each entry is a NetworkBehaviour prefab spawned by missions during setup via Mission.SpawnAndAddObjective(prefab). Keyed by gameObject.name (e.g. "Cleanup Detail Objective", "Power Decommissioners Objective", "Extract Objective"). The same key is used by mission RawData @ref fields ("objective:<Name>").
   */
  objectives: {
    [k: string]: ObjectiveEntry;
  };
  /**
   * World-region catalog from Global.Instance.Regions, keyed by stringified WorldRegion.ID. Regions group scenes (e.g. "tundra", "desert", "city") and define playable level pools.
   */
  regions: {
    [k: string]: Region;
  };
  /**
   * Enemy catalog from EnemyClass ScriptableObjects, keyed by EnemyClass.ID stringified. Includes full per-enemy combat stats (movement, melee, ragdoll, navigation, limb regrowth) under Config.
   */
  enemies: {
    [k: string]: Enemy;
  };
  /**
   * Status-effect catalog (StatusEffectData ScriptableObjects), keyed by effectID (e.g. "el_fire", "el_acid", "el_decay"). Carries display metadata, color theming, and stage counts; numerical effect math (DPS, durations) is encoded on consumer code rather than the SO.
   */
  statusEffects: {
    [k: string]: StatusEffect;
  };
  /**
   * Stacking modifier catalog (PlayerStackData), keyed by internal stack name (e.g. "scrap", "wildfire", "dmr_boost"). Defines how player buffs/debuffs accumulate, decay, and time out.
   */
  stacks: {
    [k: string]: Stack;
  };
  /**
   * Threat-tier catalog (ThreatData), keyed by internal threat name ("threat1" through "threat7"). Drives mission difficulty scaling and per-tier reward pools.
   */
  threats: {
    [k: string]: Threat;
  };
  /**
   * Mission-modifier catalog (MissionModifier subclasses including MissionModifierGeneric, MissionModifierWaveModifier, and game-specific modifiers like MissionModifierHorde), keyed by stringified ID. Used by the weekly mission-modifier rotation system.
   */
  missionModifiers: {
    [k: string]: MissionModifier;
  };
  /**
   * Weighted upgrade pools used by mission rewards (e.g. via `LevelUnlock_LootPool.LootPool`). Keyed by ScriptableObject asset name (e.g. "Amalg1Upgrades", "Amalg1Skins").
   */
  lootPools: {
    [k: string]: LootPool;
  };
  /**
   * Master localization table dumped from `TextBlocks.strings` — the single dictionary every game-displayed string flows through (`TextBlocks.GetString(key)`). Keys are short identifiers; values are arrays of text blocks. Stat labels: `force` → "Force", `dam_min` → "Min Damage", `firerate` → "Fire Rate", etc. Per-upgrade entries: each upgrade has a localization entry keyed by its `APIName` with `[0] = Name` and `[1] = Description` (when present). Currently English-only — Mycopunk's runtime loads one locale at game start.
   */
  localization: {
    [k: string]: Localization;
  };
  player?: PlayerBase;
  /**
   * AuthItem catalog — in-fiction "redemption code" items. 4 entries (auth_bruiser, auth_glider, auth_scrapper, auth_wrangler), each granting its character + a starter upgrade. Keyed by item ID.
   */
  authItems: {
    [k: string]: AuthItem;
  };
  /**
   * Special hex-grid pattern definitions. 7 entries. When the upgrade grid contains the pattern, the player gets the listed `Rewards`. Keyed by stringified `ID`.
   */
  patternPaths: {
    [k: string]: PatternPath;
  };
  /**
   * Per-threat-level scaling curves (ThreatModifierProfile). Each profile's `Threats` array is indexed 0..6 (threat1..threat7). Used by various game systems to scale e.g. modifier chances, reward rates, and enemy stats with mission threat. Keyed by SO asset name.
   */
  threatProfiles: {
    [k: string]: ThreatProfile;
  };
  /**
   * Wave-composition specs (CustomWave subclasses, primarily GenericCustomWave). Used by the spawn system to control the enemy mix per mission/event: tag filters, type filters, weighted chances, count multipliers, room-size constraints. Keyed by SO asset name.
   */
  customWaves: {
    [k: string]: CustomWave;
  };
  /**
   * World-collectable definitions (CollectableProfile). When the player fully collects a target (e.g. a pump), the `Rewards` list fires. Keyed by `nameID`.
   */
  collectables: {
    [k: string]: Collectable;
  };
  /**
   * Weighted groupings of `EnemyClass` values (EnemyClassGroup). Used by the spawn system to vary enemy mix within a single EnemyType. Keyed by SO asset name.
   */
  enemyGroups: {
    [k: string]: EnemyGroup;
  };
  /**
   * Timed/seasonal global events (e.g. Amalgamation Hunt, Corp Contest). Each has progress thresholds, end-mission cross-references, reward lists, and subclass-specific tunables. Keyed by event ID.
   */
  globalEvents: {
    [k: string]: GlobalEvent;
  };
  /**
   * Non-grid player upgrades — character movement abilities (AirDashUpgrade for Wrangler, NoseDiveUpgrade for Bruiser, JetpackUpgrade for Scrapper, plus skill-tree movement modifiers like Blink, DiveCancel, Splash Zone). Each entry's `RawData` carries the full prefab data including `Cooldown` config and ability-specific nested Data structs. Keyed by SO asset name.
   */
  playerUpgrades: {
    [k: string]: PlayerUpgradeEntry;
  };
  statusEffectGlobals: StatusEffectGlobals;
  formulas: Formulas;
  /**
   * Steam achievement IDs scraped from `Online.UnlockAchievement(...)` call sites. No external catalog exists; the strings are scattered through gameplay code.
   */
  achievements: string[];
  /**
   * Steam stat IDs the game tracks (player progression metrics). Scraped from `Online.SetStat`/`SubmitGlobalStat` call sites.
   */
  steamStats: string[];
  /**
   * Master rarity/cost table. Per-rarity scrip cost, rare-resource cost, Ouroboros cleanse cost, saxonite craft-new cost, plus colors and the cross-referenced scrap PlayerResource. 6 entries: `standard`, `rare`, `epic`, `exotic`, `contraband`, `oddity`. Sourced from `Global.Instance.Rarities`. Keyed by `Name`.
   */
  rarities?: {
    [k: string]: RarityEntry;
  };
  /**
   * Mission-container variants — modes that wrap regular mission selection. 2 entries: `DefaultMissionContainer` and `Overtime Assignment` (the weekly mode with its scheduled modifier calendar inside `RawData.weekData`). Keyed by SO asset name.
   */
  missionContainers?: {
    [k: string]: MissionContainerEntry;
  };
  /**
   * IEncounter catalog — the procedural-mission spawn rules. 20 entries (Crater, Pipeline, Water, Meatspawn, Upgrade Drone, Lost Saxitos, Arc Gates, Scorched Transponder, Eye Wall, …). Mixed `UnityEngine.Object[]` (some entries are SO impls, others are GameObject prefabs whose component implements IEncounter). Per-encounter parameters live in `RawData`. Keyed by asset name; cross-referenced via `@ref:"encounter:<Name>"`.
   */
  encounters?: {
    [k: string]: EncounterEntry;
  };
  /**
   * Master player emote/quip catalog. 63 entries across 4 characters; the same `Label` can repeat across characters so the keys here are the numeric `ID` stringified. Each entry has the spoken voiceline ID (resolves in `localization`), animation clip names, and the character it belongs to.
   */
  quips?: {
    [k: string]: QuipEntry;
  };
  crafting?: Crafting;
  dialogue?: DialogueData;
  /**
   * Named bundles of `UpgradeProperty` overrides referenced by `SkinUpgradeProperty_Preset.preset` (e.g. "Coppertone", "Bloodmetal", "Glittering"). Each preset's `Modifiers` mirrors `Skin.Modifiers` so a consumer can answer "what does Glittering do?" without parsing `RawData`. Catalog source: `Resources.FindObjectsOfTypeAll<UpgradePreset>()`. Keyed by SO asset name.
   */
  upgradePresets?: {
    [k: string]: UpgradePresetEntry;
  };
}
/**
 * A single upgrade definition (a hex-grid module that modifies gear or characters).
 */
export interface Upgrade {
  /**
   * Stringified UpgradeID — vanilla bare integer, modded "<Mod>:<ID>". Matches the parent map's key.
   */
  ID: string;
  /**
   * Stable internal API name (snake_case-ish, often matches asset filename).
   */
  APIName: string;
  /**
   * Localized display name. May include rich-text tags (<color=...>, <link=...>).
   */
  Name: string;
  /**
   * Effect-element classification (Normal, Fire, Acid, Electric, etc.) — enum stringified.
   */
  EffectType: string;
  /**
   * Upgrade category (Normal, Skin, etc.) — Upgrade+Type enum stringified.
   */
  UpgradeType: string;
  /**
   * Rarity tier (Standard, Rare, Epic, Exotic).
   */
  Rarity: string;
  /**
   * Comma-separated flag-enum string from UpgradeFlags (e.g. "CanStack, CanStackInMission").
   */
  Flags: string;
  /**
   * Theme color as Unity RGBA(r, g, b, a) string.
   */
  Color: string;
  /**
   * Localized in-game description with rich-text markup.
   */
  Description?: string;
  /**
   * Display string of a prerequisite upgrade that must be unlocked before this one. Stringified at dump time; can be cross-referenced by Name.
   */
  MustBeUnlockedFirst?: string | null;
  Pattern?: HexMap;
  Icon?: DIcon;
  Skin?: DSkin;
  /**
   * Per-property data for this upgrade. Each entry pairs a property class name (Type) with the raw Unity-serialized config (Raw) and a per-upgradable expansion of evaluated stats (StatsByUpgradable).
   */
  Properties?: UpgradeDProperty[];
  /**
   * Resources required to unlock this upgrade.
   */
  UnlockCost?: DUnlockCost[];
  /**
   * Secondary cost surface (e.g. crafting cost on top of the unlock cost).
   */
  AdditionalUnlockCost?: DUnlockCost[] | null;
  /**
   * List of upgradables that can equip this upgrade. Each entry's APIName is a key into gears or characters. The Name is human-readable ("<DisplayName> (<C# class>)").
   */
  ApplicableTo: DUpgradeable[];
  /**
   * Display sort priority; the upgrade browser sorts ascending by this.
   */
  Priority?: number;
  /**
   * How the upgrade is obtained.
   */
  CollectionSource?:
    | "WorldPool"
    | "None"
    | "UpgradeTree"
    | "DropsFromSource"
    | "HiddenAlways"
    | "HiddenIfNotOwned"
    | "Beta"
    | "LevelUp"
    | "Resources";
  /**
   * True for upgrades introduced by mods (non-empty UpgradeID.Mod).
   */
  IsModded?: boolean;
  /**
   * BepInEx plugin GUID that registered this upgrade. Empty for vanilla.
   */
  ModGUID?: string;
  /**
   * Resources required to turbocharge this upgrade (Upgrade.GetTurbochargeCost() result). Exotic upgrades have a flat formula (100 of each rare-fungi + 1 strange components); other rarities pull from a seeded random selection. Always populated; values vary by Rarity and NumberID seed.
   */
  TurbochargeCost?: DUnlockCost[];
  /**
   * Cost to take this upgrade in Ouroboros mode (Upgrade.GetOuroborosCost()). Formula: 5 + Rarity*2 ouroscrap (Standard=5, Rare=7, Epic=9, Exotic=11).
   */
  OuroborosCost?: DUnlockCost[];
}
/**
 * Hex-grid pattern of an upgrade or grid layout. Serialized via UnityEngine.JsonUtility.
 */
export interface HexMap {
  /**
   * Number of columns.
   */
  width?: number;
  /**
   * Number of rows.
   */
  height?: number;
  /**
   * Row-major 2D grid of node arrays. Each cell carries an enabled flag and a bitmask of edge connections to neighboring cells.
   */
  nodes?: {
    nodes?: {
      enabled?: boolean;
      /**
       * Bitmask of edge connections (6 bits, one per hex side).
       */
      connections?: number;
    }[];
  }[];
}
/**
 * Sprite icon reference. The dump does not embed the sprite image — it stores only the texture-atlas name and source rect, so consumers must fetch the actual texture from the game install separately.
 */
export interface DIcon {
  /**
   * Source rect within the parent texture, in pixels: [xMin, yMin, width, height].
   *
   * @minItems 4
   * @maxItems 4
   */
  Rect?: [number, number, number, number];
  /**
   * Name of the texture-atlas asset.
   */
  Texture?: string;
}
/**
 * Cosmetic-specific data, populated only when `UpgradeType` == `"Cosmetic"` (i.e. the upgrade is a `SkinUpgrade`). Aggregates fields scattered across `SkinUpgrade` and its `SkinUpgradeProperty` subclasses.
 */
export interface DSkin {
  /**
   * Upgrade key — parent skin this inherits visuals from (or absent for root skins). Lookup target in the parent `upgrades` map.
   */
  BaseSkin?: string;
  /**
   * Upgrade key — codex-collection alias (e.g. "Factory" and "Factory (Bloodmetal)" share a single codex slot). Lookup target in `upgrades`.
   */
  CountWithInCodex?: string;
  /**
   * 0..1 — probability this skin is removed from the world drop pool after rolling once.
   */
  ChanceToRemoveFromPool?: number;
  /**
   * Whether the icon is tinted by the skin color at render time.
   */
  ColorIcon?: boolean;
  ChangeHueIfNoModifiersApplied?: boolean;
  /**
   * True when `SkinUpgrade.overridePattern` is set — the skin tree uses a non-default `HexMapProfile`. Default is `Global.Instance.SkinPattern`.
   */
  OverridesPattern?: boolean;
  /**
   * Any VFX-spawning property is present (GunCrab-derived, VFXMod, VFXCustomProp). Skins with this flag run a `VisualEffect` that needs manual ticking when `Time.timeScale = 0`.
   */
  HasVfx?: boolean;
  /**
   * Any GunCrab-derived property — the gun gets a crab/eye/pump/roach companion prop spawned next to it.
   */
  HasCrab?: boolean;
  /**
   * Any `SkinUpgradeProperty_CharacterModel` — replaces the player's first/third-person mesh.
   */
  HasCharacterModel?: boolean;
  IconAtlas?: DIconAtlas;
  /**
   * Distinct instance-name modifier suffixes observed via deterministic seed sweep over `SkinUpgrade.GetInstanceName(seed)` for seeds 0..63. Entries are the parenthesised inner part — e.g. "Bloodmetal", "Spectral, Sapphire". Useful for UI dropdowns and codex grouping.
   */
  NameModifiers?: string[];
  /**
   * Per-property summary. Walked over `SkinUpgrade.GetProperties()` (which inlines properties inherited from `BaseSkin`). Each entry resolves the most useful subclass-specific fields; consumers that need everything can fall back to the corresponding `Properties[i].Raw` on the parent upgrade.
   */
  Modifiers?: DSkinModifier[];
  /**
   * Per-(gear, preset) relative paths to rendered mp4 turntables. Outer key: gear APIName (matches `gears`/`characters`). Inner key: preset slug — `"base"` for the no-preset rotation, otherwise the sanitized preset SO name (matches the slug used by the SkinRenderer task). Value: path relative to the base extracted-dump directory (e.g. `~/MycopunkExtracted/<version>/`). The file at the path may or may not exist depending on whether the renderer has run; the path is computed from the slug pattern, not from disk.
   */
  Previews?: {
    [k: string]: {
      [k: string]: string;
    };
  };
}
/**
 * Raw atlas-cropping data so consumers can pull the source pixels from the original sprite sheet without re-running `Sprite.Create`. Position/Size are pre-scaling; the actual displayed rect is `position * (atlasWidth / TextureSize)`, `size * (atlasWidth / TextureSize)` (see `SkinUpgrade.Icon` getter).
 */
export interface DIconAtlas {
  /**
   * Source `Texture2D` asset name.
   */
  Texture?: string;
  /**
   * `SkinUpgrade.textureSize` (defaults to 4096) — divisor for the position/size scale factor against the actual atlas resolution.
   */
  TextureSize?: number;
  /**
   * [x, y] in atlas pixel-coordinates (pre-scaling).
   *
   * @minItems 2
   * @maxItems 2
   */
  Position?: [number, number];
  /**
   * [w, h] in atlas pixel-coordinates (pre-scaling).
   *
   * @minItems 2
   * @maxItems 2
   */
  Size?: [number, number];
}
/**
 * Resolved summary of one `SkinUpgradeProperty` (or any `UpgradeProperty`) entry. Field families are mutually exclusive — only fields tagged for the property's `Type` are populated, the rest are absent. Fall back to the parent's `Properties[i].Raw` when this summary doesn't cover the field you need.
 */
export interface DSkinModifier {
  /**
   * Concrete C# class name (e.g. "SkinUpgradeProperty_Trim").
   */
  Type: string;
  /**
   * Roll chance (0..1). Null when the subclass doesn't expose one OR when chance is meaningless because the property always applies (`SkinUpgradeProperty_Texture`/`_Color` whose `GetPropertyChance` is constant 1).
   */
  Chance?: number | null;
  /**
   * True when the property's `AnimationCurve` evaluates to the same value at 0 and 1 — i.e. the curve is acting as a chance gate rather than a roll distribution. Null when no curve is present.
   */
  CurveConstant?: boolean | null;
  /**
   * `curve.Evaluate(0)` — start of the rolled-value distribution.
   */
  CurveStart?: number;
  /**
   * `curve.Evaluate(1)` — end of the rolled-value distribution.
   */
  CurveEnd?: number;
  /**
   * SkinUpgradeProperty_Trim — TextBlocks key for the trim's display name.
   */
  TrimID?: string;
  /**
   * Resolved trim name (e.g. "Sapphire", "Topaz").
   */
  TrimName?: string;
  /**
   * RGBA(...) — base trim color.
   */
  TrimColor?: string;
  /**
   * RGBA(...) — specular tint applied alongside trimColor.
   */
  TrimSpecular?: string;
  /**
   * 0..1 — chance the trim's hue is shifted instead of using the literal trimColor.
   */
  TrimHueChance?: number;
  /**
   * -1..1 — max hue-shift magnitude when the hue roll fires.
   */
  TrimMaxHue?: number;
  TrimFlip?: boolean;
  TrimAlpha?: boolean;
  /**
   * SkinUpgradeProperty_Preset — `UpgradePreset` SO asset name. Lookup target in the top-level `upgradePresets` map.
   */
  Preset?: string;
  /**
   * SkinUpgradeProperty_Texture — name of the source Material the texture-replacement targets ("find this material, swap it").
   */
  TextureFind?: string;
  /**
   * Replacement albedo `Texture2D` asset name.
   */
  TextureMain?: string;
  /**
   * Replacement specular `Texture2D` asset name.
   */
  TextureSpecular?: string;
  TextureOverrideColor?: boolean;
  /**
   * RGBA(...) — only meaningful when `TextureOverrideColor` is true.
   */
  TextureColor?: string;
  /**
   * RGBA(...) — only meaningful when `TextureOverrideColor` is true.
   */
  TextureShadowColor?: string;
  TextureOverrideSpecularColor?: boolean;
  /**
   * RGBA(...) — only meaningful when `TextureOverrideSpecularColor` is true.
   */
  TextureSpecularColor?: string;
  TextureOverrideSmoothness?: boolean;
  /**
   * Only meaningful when `TextureOverrideSmoothness` is true.
   */
  TextureSmoothness?: number;
  /**
   * SkinUpgradeProperty_Color — RGBA(...) primary tint applied to `_Color` shader prop.
   */
  ColorPrimary?: string;
  /**
   * RGBA(...) shadow tint applied to `_ShadowColor`.
   */
  ColorShadow?: string;
  /**
   * `Range<int> materialRange.min` — restricts which override-mat indices receive the tint.
   */
  ColorMaterialMin?: number;
  ColorMaterialMax?: number;
  /**
   * SkinUpgradeProperty_Chroma.
   */
  ChromaSunBrightness?: number;
  ChromaShadowBrightness?: number;
  /**
   * SkinUpgradeProperty_Emissive — TextBlocks key for the modifier's display name.
   */
  EmissiveStatID?: string;
  /**
   * Resolved name.
   */
  EmissiveStatName?: string;
  /**
   * RGBA(HDR).
   */
  EmissiveColor?: string;
  EmissiveHueChance?: number;
  EmissiveMaxHue?: number;
  EmissiveFlipTrim?: boolean;
  /**
   * SkinUpgradeProperty_Neon — channel intensity per primary.
   */
  NeonRed?: number;
  NeonGreen?: number;
  NeonBlue?: number;
  NeonYellow?: number;
  NeonMagenta?: number;
  NeonFlipTrim?: boolean;
  /**
   * SkinUpgradeProperty_Contrast — contrast value applied uniformly.
   */
  Contrast?: number;
  /**
   * SkinUpgradeProperty_ContrastRange.
   */
  ContrastRangeLabelID?: string;
  /**
   * Resolved.
   */
  ContrastRangeLabel?: string;
  /**
   * SkinUpgradeProperty_Overlay only (Empty for `_OverlayMat`). TextBlocks key for the overlay's display name.
   */
  OverlayID?: string;
  /**
   * Resolved overlay label.
   */
  OverlayLabel?: string;
  /**
   * `overlayTex` asset name (both _Overlay and _OverlayMat).
   */
  OverlayTexture?: string;
  /**
   * _Overlay only.
   */
  OverlayBoost?: number;
  OverlayTile?: number;
  OverlayTriplanar?: boolean;
  /**
   * SkinUpgradeProperty_TrickOrTreat — RGBA(...).
   */
  TrickColor?: string;
  /**
   * RGBA(...).
   */
  TreatColor?: string;
  TrickHueChance?: number;
  TrickRandHueIntensity?: number;
  TrickFlipTrim?: boolean;
  /**
   * SkinUpgradeProperty_Infection.
   */
  InfectionScale?: number;
  /**
   * SkinUpgradeProperty_GunCrab (and subclasses) — `crab` GameObject prefab asset name.
   */
  CrabModel?: string;
  /**
   * Upgrade key (`SkinUpgradeProperty_GunCrab.myUpgrade`). Lookup in `upgrades`.
   */
  CrabUpgrade?: string;
  /**
   * SkinUpgradeProperty_GunCrab_List — pool of mesh asset names the crab variant rolls between.
   */
  CrabMeshes?: string[];
  /**
   * SkinUpgradeProperty_VFXCrab — TextBlocks key for the VFX variant's display name.
   */
  VfxCrabNameID?: string;
  /**
   * Resolved.
   */
  VfxCrabName?: string;
  /**
   * Rarity-enum stringified — name display tier.
   */
  VfxCrabNameColor?: string;
  /**
   * -1 = no override; otherwise overrides the prefab VFX `Size` parameter.
   */
  VfxCrabSizeOverride?: number;
  VfxCrabIntensityOverride?: number;
  VfxCrabRateOverride?: number;
  VfxCrabLongevityOverride?: number;
  VfxCrabOverrideSpeed?: boolean;
  VfxCrabSpeedOverride?: number;
  VfxCrabOverrideColor?: boolean;
  /**
   * RGBA(HDR) — only meaningful when `VfxCrabOverrideColor` is true.
   */
  VfxCrabColor1?: string;
  /**
   * RGBA(HDR) — only meaningful when `VfxCrabOverrideColor` is true.
   */
  VfxCrabColor2?: string;
  VfxCrabAlphaOverride?: number;
  /**
   * SkinUpgradeProperty_VFXCustomProp — name of the VFX shader/expression property being overridden.
   */
  VfxCustomPropName?: string;
  /**
   * Float / Float2 / Float3 / Float4.
   */
  VfxCustomPropType?: string;
  /**
   * Vector4 unpacked to [x, y, z, w]. Only the first N components are meaningful per `VfxCustomPropType`.
   *
   * @minItems 4
   * @maxItems 4
   */
  VfxCustomPropValue?: [number, number, number, number];
  /**
   * SkinUpgradeProperty_CharacterModel — `firstPersonArmL` SkinnedMeshRenderer mesh asset name.
   */
  CharacterModelArmL?: string;
  /**
   * `firstPersonArmR` mesh asset name.
   */
  CharacterModelArmR?: string;
  /**
   * `thirdPersonMesh` mesh asset name.
   */
  CharacterModelThirdPerson?: string;
}
/**
 * One UpgradeProperty instance attached to an upgrade.
 */
export interface UpgradeDProperty {
  /**
   * C# class name of the concrete UpgradeProperty subclass, e.g. UpgradeProperty_SMG_FastReloadOnKill.
   */
  Type: string;
  /**
   * Human-readable form of `Type` — strips the `UpgradeProperty_` prefix and splits CamelCase / underscores. E.g. `UpgradeProperty_Bruiser_Cannonball` → "Bruiser Cannonball", `UpgradeProperty_AmmoCapacity` → "Ammo Capacity". Convenience field for UI display.
   */
  Label?: string;
  /**
   * Distinct stat labels this property emits via `GetStatData()` (sorted, with rich-text tags stripped). For example `UpgradeProperty_Bruiser_Cannonball` emits stats labelled `Force`, `Min Damage`, `Max Damage`, `Min Radius`, `Max Radius`. Empty (or absent) when the property modifies behavior without producing tooltip stats. **Note:** the game's tooltip ALSO renders text from `ModifyProperties` — see `ModifyTextLines` for that second source.
   */
  StatNames?: string[];
  /**
   * Free-form tooltip text produced by `UpgradeProperty.ModifyProperties(ref string, ...)` — the second tooltip source after `StatData`. Captured by invoking the method against each upgradable that can equip this upgrade. Often blank, but for some properties this is the ONLY place the meaningful stat label shows up. Examples: the four Mini Cannon Prism upgrades all share `UpgradeProperty_MiniCannon_Prism` with `StatNames: ["Efficiency"]`, but each Prism's actual color-coded stat (`Range`, `Spread`, `Fire Rate`, `Damage`) is only here. Values include rich-text color tags as the game would render them; consumers wanting plain text should use `ModifyTextLines`.
   */
  ModifyTextByUpgradable?: {
    [k: string]: string;
  };
  /**
   * Distinct lines pulled from `ModifyTextByUpgradable` with rich-text tags stripped, sorted. Use for indexing/filtering upgrades by their actual displayed labels.
   */
  ModifyTextLines?: string[];
  /**
   * Every localization key (`TextBlocks.GetString` argument) that this property's source code references — including keys hidden behind switch expressions or conditional branches that runtime sampling can't trigger. Extracted by static analysis of the decompiled property class. Cross-reference into the top-level `localization` map. Only present when the optional `mise run extract-labels` step has produced `property-labels.json`. Example: `UpgradeProperty_MiniCannon_Prism` has keys `["damage", "efficiency", "firerate", "range", "spread"]` covering all four prism-rarity branches.
   */
  LocalizationKeys?: string[];
  /**
   * Unity-serialized config for the property — fields and values vary per subclass. Serialized via UnityEngine.JsonUtility.ToJson, so the structure is whatever the property's [SerializeField] schema exposes.
   */
  Raw?: {
    [k: string]: unknown;
  };
  /**
   * Evaluated stat data per upgradable that can equip this upgrade. Keys are upgradable APINames (matching gears / characters); values are the ordered output of UpgradeProperty.GetStatData(...) seeded with 0 — a single representative roll. For random/categorical stats see `RolledValuesByUpgradable`.
   */
  StatsByUpgradable?: {
    [k: string]: StatData[];
  };
  /**
   * Distinct stat `value` strings observed across 16 deterministic seeded samples of `GetStatData(...)` per upgradable. Captures the full set of outcomes for stats that roll non-deterministically — most importantly **categorical** rolls like the random element from `GetRandomEffect()` returning `{Fire, Shock, Acid}` (or `{Normal, Fire, Shock, Acid}` for `GetRandomEffectIncludingNormal()`). Outer key: upgradable APIName. Inner key: stat name (rich-text intact). Inner value: sorted array of all observed `value` strings (rich-text intact). Only stats where >1 distinct value was seen are recorded — deterministic stats are absent. Numeric stats may also appear, in which case the array shows the distribution of sampled values within the existing `minValue`/`maxValue` range (useful for distribution analysis; redundant with the range if you don't need it).
   */
  RolledValuesByUpgradable?: {
    [k: string]: {
      [k: string]: string[];
    };
  };
}
/**
 * A single labelled stat shown in the upgrade tooltip. Game type StatData from UnityEngine.JsonUtility.
 */
export interface StatData {
  /**
   * Stat label, may include rich-text color tags.
   */
  name?: string;
  /**
   * Display value (often pre-formatted, e.g. "+7", "x1.25").
   */
  value?: string;
  /**
   * Lower-bound display value (when the stat rolls in a range).
   */
  minValue?: string;
  /**
   * Upper-bound display value.
   */
  maxValue?: string;
  /**
   * Game-internal StatData+LabelType enum.
   */
  labelType?: number;
  /**
   * Game-internal OverrideType enum.
   */
  overrideType?: number;
  /**
   * UI hint — render this stat after others.
   */
  placeAtEnd?: boolean;
  /**
   * Optional message shown when the stat stacks.
   */
  stackMessage?: string;
  /**
   * Boost behavior parameters (e.g. when an upgrade is turbocharged).
   */
  boostParams?: {
    cannotBeBoosted?: boolean;
    minIsBetter?: boolean;
  };
  /**
   * Whether the stat is renderable; some entries are LineBreak() separators.
   */
  IsValid?: boolean;
}
/**
 * One line item in an unlock cost (resource + count).
 */
export interface DUnlockCost {
  /**
   * Number of units required.
   */
  Count: number;
  /**
   * Display name of the resource (e.g. "Saxonite"). Legacy field; matches PlayerResource.Name.
   */
  Resource?: string;
  /**
   * Canonical key into resources (e.g. "saxonite"). Added in v2.0; prefer this over Resource for cross-referencing.
   */
  ResourceID?: string;
}
/**
 * A back-reference from an upgrade to a gear/character that can equip it.
 */
export interface DUpgradeable {
  /**
   * Human-readable form, "<DisplayName> (<C# class>)", e.g. "Bruiser (Character)".
   */
  Name: string;
  /**
   * Canonical key into gears or characters. Note: prior to v2.0 this was the C# class name (collapsing all four characters under "Character"); it now uses GearInfo.APIName.
   */
  APIName: string;
}
/**
 * A non-character upgradable (weapon, grenade, utility, vehicle, etc.).
 */
export interface Gear {
  /**
   * Numeric GearInfo.ID stringified.
   */
  ID: string;
  /**
   * Localized display name.
   */
  Name: string;
  /**
   * Canonical key (matches the parent map's key).
   */
  APIName: string;
  /**
   * Subtype description shown in UI (e.g. "Accelerating Burst SMG").
   */
  TypeName?: string;
  /**
   * Localized in-game description with rich-text markup.
   */
  Description?: string;
  /**
   * Category enum stringified.
   */
  GearType: "Primary" | "Heavy" | "Utility" | "Throwable" | "Melee" | "Character" | "Vehicle" | "Custom";
  /**
   * Highest XP level the gear can reach.
   */
  MaxLevel?: number;
  /**
   * Player level required before this gear becomes available.
   */
  MinUnlockLevel?: number;
  /**
   * If true, unlocks without spending UnlockCost.
   */
  UnlockAutomatically?: boolean;
  /**
   * UI hint — hide from collection screens until obtained.
   */
  HideWhenNotCollected?: boolean;
  /**
   * Whether the gear levels up via XP gain.
   */
  CanGainXP?: boolean;
  /**
   * Whether the gear has an upgrade grid at all.
   */
  HasUpgradeGrid?: boolean;
  /**
   * Multiplier on XP gained. Note: stored as XPGainMultilier (sic) in the game; the dumper renames to the corrected spelling.
   */
  XPGainMultiplier?: number;
  /**
   * Multiplier on directive-kill counts when this gear is equipped.
   */
  DirectiveKillsMultiplier?: number;
  /**
   * Number of skin upgrades available for this gear.
   */
  SkinCount?: number;
  /**
   * Resources required to unlock the gear itself.
   */
  UnlockCost?: DUnlockCost[];
  /**
   * Upgrade-grid dimensions per gear level. Index 0 is base; higher indices are dimensions after each level-up reward expands the grid.
   */
  GridSizes?: GridSize[];
  /**
   * Rewards granted at gear level-up milestones. The discriminator is Type.
   */
  LevelUnlocks?: LevelUnlockEntry[];
  Icon?: DIcon;
  /**
   * Full Unity-serialized prefab data — every `[SerializeField]` field on the gear's `MonoBehaviour`. Schema is per-gear-class and not formally typed here. Where to look for combat stats: guns have `gunData` (`damage`, `bulletSpeed`, `fireInterval`, `bulletsPerShot`, `magazineSize`, `ammoCapacity`, `reloadDuration`, `recoilData.*`, `spreadData.*`, `rangeData.maxDamageRange`); grenades have `gunData` + `cooldownData.rechargeDuration`; melee/throwables have analogous containers. Leaves of the form `{ "instanceID": N }` are references to other Unity assets. When the referenced asset is a top-level catalog entry, the dumper enriches the leaf with `"@ref": "<type>:<key>"` (e.g. `"@ref": "upgrade:99770"`, `"@ref": "stack:scrap"`) so consumers can resolve it without a separate index. Refs without `@ref` point to non-catalog assets (animation clips, materials, sprites, sounds) and are safe to ignore.
   */
  RawData?: {
    [k: string]: unknown;
  };
}
/**
 * Upgrade-grid dimensions for a single gear level.
 */
export interface GridSize {
  Width?: number;
  Height?: number;
}
/**
 * One reward entry from GearInfo.LevelUnlocks or DirectiveData.AdditionalRewards. Discriminated by Type. Fields beyond the common ones are populated based on the subclass — readers can treat absent fields as not applicable.
 */
export interface LevelUnlockEntry {
  /**
   * C# class name of the concrete LevelUnlock_* subclass.
   */
  Type:
    | "LevelUnlock_Resource"
    | "LevelUnlock_MultipleUpgrades"
    | "LevelUnlock_UpgradeRarity"
    | "LevelUnlock_SkinRarity"
    | "LevelUnlock_SeededSkin"
    | "LevelUnlock_XP"
    | "LevelUnlock_Upgrade"
    | "LevelUnlock_LootPool"
    | "LevelUnlock_Skin"
    | "LevelUnlock_Gear"
    | "LevelUnlock_IntroUpgrade"
    | "LevelUnlock_Preview"
    | "LevelUnlock_RarityReward";
  /**
   * Gear/directive level at which this reward is granted. For mission and directive rewards, often 0 (chance-based).
   */
  Level?: number;
  /**
   * Number of times the reward fires.
   */
  Count?: number;
  /**
   * Probability (0..1) the reward triggers; 1.0 means deterministic, 0 means deterministic-but-weighted-elsewhere.
   */
  Chance?: number;
  Resource?: DUnlockCost1;
  /**
   * Set on LevelUnlock_MultipleUpgrades. If true, the game prefers granting upgrades the player hasn't unlocked yet.
   */
  PrioritizeUndiscovered?: boolean;
  /**
   * Set on LevelUnlock_MultipleUpgrades. List of upgrade keys (matching keys in the top-level upgrades map). The reward grants Count of them, optionally weighted by PrioritizeUndiscovered.
   */
  Upgrades?: string[];
  /**
   * Set on LevelUnlock_UpgradeRarity, LevelUnlock_SkinRarity, and LevelUnlock_RarityReward. Rarity tier of the upgrade/skin/reward granted. "None" appears for unspecified.
   */
  Rarity?: "Standard" | "Rare" | "Epic" | "Exotic" | "None";
  /**
   * Set on LevelUnlock_XP. Amount of player XP granted.
   */
  XP?: number;
  /**
   * Upgrade key. Set on LevelUnlock_Upgrade (specific upgrade reward) and LevelUnlock_SeededSkin (specific SkinUpgrade).
   */
  Upgrade?: string;
  /**
   * Set on LevelUnlock_LootPool. Name of the LootPool ScriptableObject from which a random reward is drawn.
   */
  LootPool?: string;
  /**
   * Set on LevelUnlock_LootPool. Minimum level for items pulled from the loot pool.
   */
  MinLevel?: number;
  /**
   * Set on LevelUnlock_Gear. Name of the gear GameObject prefab being unlocked or locked.
   */
  Gear?: string;
  /**
   * Set on LevelUnlock_Gear. true = unlock gear; false = the gear is locked at this level.
   */
  Unlock?: boolean;
  /**
   * Set on LevelUnlock_IntroUpgrade. First upgrade in the tutorial pair.
   */
  Upgrade1?: string;
  /**
   * Set on LevelUnlock_IntroUpgrade. Second upgrade in the tutorial pair.
   */
  Upgrade2?: string;
  /**
   * Set on LevelUnlock_Preview. Internal nameID being previewed (e.g. "xp").
   */
  Preview?: string;
  /**
   * Set on LevelUnlock_SeededSkin. Random seed used to roll the SkinUpgrade variant.
   */
  Seed?: number;
}
/**
 * One line item in an unlock cost (resource + count).
 */
export interface DUnlockCost1 {
  /**
   * Number of units required.
   */
  Count: number;
  /**
   * Display name of the resource (e.g. "Saxonite"). Legacy field; matches PlayerResource.Name.
   */
  Resource?: string;
  /**
   * Canonical key into resources (e.g. "saxonite"). Added in v2.0; prefer this over Resource for cross-referencing.
   */
  ResourceID?: string;
}
/**
 * A voice line / emote entry.
 */
export interface Quip {
  /**
   * Numeric quip ID.
   */
  ID?: number;
  /**
   * Stable index within the character's quip list.
   */
  Index?: number;
  /**
   * Stable internal name (e.g. "e_yes", "vl_help").
   */
  APIName?: string;
  /**
   * UI label.
   */
  Label?: string;
  /**
   * Localization key for the spoken text.
   */
  VoicelineTextID?: string;
  /**
   * Game-internal QuipData+Type enum stringified.
   */
  QuipType?: string;
  /**
   * Whether the quip fires automatically on weapon fire.
   */
  TriggerOnFire?: boolean;
  /**
   * Whether the quip has audio (versus text-only).
   */
  HasVoiceline?: boolean;
  Icon?: DIcon;
}
/**
 * One node in a character's skill tree.
 */
export interface SkillTreeNode {
  /**
   * Upgrade key granted by purchasing this node (matches `upgrades` map key).
   */
  Upgrade: string;
  /**
   * Tier in the tree (0 = root, 1, 2, …, max observed = 5).
   */
  Layer: number;
  /**
   * Computed gate: layer 0 = 0; otherwise `2 + (layer - 1) * 5`. The player must have spent at least this many skill points elsewhere in the tree before this node unlocks.
   */
  MinSpentSkillPointsToUnlock?: number;
  /**
   * Visual grid X coordinate.
   */
  CoordX?: number;
  /**
   * Visual grid Y coordinate.
   */
  CoordY?: number;
  /**
   * Upgrade key — prerequisite node that must be unlocked before this one. Null/empty for root-layer nodes.
   */
  MustBeUnlockedFirst?: string;
}
/**
 * A PlayerResource — a unit in the game economy. Includes currencies (Gats, Saxonite), faction tickets, items (Premium Loot License), and crafting materials (Strange Components).
 */
export interface Resource {
  /**
   * Canonical key (matches parent map's key).
   */
  ID: string;
  /**
   * Display name (may include rich-text tags).
   */
  Name: string;
  /**
   * Localized description with rich-text markup.
   */
  Description?: string;
  /**
   * Theme color as Unity RGBA(r, g, b, a) string.
   */
  Color?: string;
  /**
   * Tint applied to Icon.
   */
  IconColor?: string;
  /**
   * Maximum stack/inventory cap.
   */
  Max?: number;
  /**
   * Currently-held player-state count at dump time. Note: this reflects the dumper's player save and isn't part of the catalog itself; consumers building UI off the catalog should ignore this field.
   */
  ItemCount?: number;
  /**
   * Default number of resources spent per unlock action.
   */
  UnlockUseCount?: number;
  /**
   * Rate at which the resource drains during a hold-to-unlock action.
   */
  UnlockUsePerSecond?: number;
  /**
   * Rarity tier.
   */
  Rarity?: "Standard" | "Rare" | "Epic" | "Exotic";
  /**
   * UI visibility policy from PlayerResource+VisibilityOptions (e.g. AlwaysShow).
   */
  Visibility?: string;
  IsAmountAffectedByDifficulty?: boolean;
  /**
   * Whether the resource is an item (unique slot) vs. a stackable currency.
   */
  IsItem?: boolean;
  Icon?: DIcon;
}
/**
 * A directive — a mission modifier the player can equip for tougher missions and additional rewards. Each Directive references one or more DirectiveProperty clauses (e.g. minimum kill counts, mission flags).
 */
export interface Directive {
  /**
   * Stable directive ID (also used as parent map's key, stringified).
   */
  ID: number;
  /**
   * Resolved display name (block 0 of the first property's NameID, e.g. "Cleanse", "Elemental Testing").
   */
  Name?: string;
  /**
   * Resolved description (block 1 of the first property's NameID).
   */
  Description?: string;
  /**
   * Whether the directive appears in the random selection pool.
   */
  CanBeChosen: boolean;
  Icon?: DIcon;
  TierWeights?: TierWeights;
  /**
   * Directive clauses — predicates the player must satisfy. Each entry has a Type (e.g. DirectiveProperty_Kill) and a Raw payload with subclass-specific fields (kill counts, thresholds, mission flags, …).
   */
  Properties?: DirectivePropertyEntry[];
  /**
   * Extra rewards granted on completion, on top of the mission's standard rewards. Same shape as gear LevelUnlocks.
   */
  AdditionalRewards?: LevelUnlockEntry[];
}
/**
 * Per-tier likelihood that this directive appears at each difficulty tier. Higher value = more likely to be offered.
 */
export interface TierWeights {
  Tier1?: number;
  Tier2?: number;
  Tier3?: number;
  Tier4?: number;
}
/**
 * One clause within a directive (game DirectiveProperty subclass).
 */
export interface DirectivePropertyEntry {
  /**
   * C# class name of the concrete DirectiveProperty_* subclass. Observed values: DirectiveProperty_Kill, DirectiveProperty_KillDeaths, DirectiveProperty_MeleeKills, DirectiveProperty_GearKills, DirectiveProperty_KillEnemyParts, DirectiveProperty_ElementKills, DirectiveProperty_ElementStacks, DirectiveProperty_Mission, DirectiveProperty_MissionKills, DirectiveProperty_OuroRooms, DirectiveProperty_SideObjective, DirectiveProperty_Speed, DirectiveProperty_SpeedThreshold.
   */
  Type: string;
  /**
   * Human-readable form of `Type` (prefix stripped + CamelCase split). E.g. `DirectiveProperty_KillDeaths` → "Kill Deaths".
   */
  Label?: string;
  /**
   * Localization key from the property's `NameID` (e.g. `dp_kill`, `dp_kill_e`, `dp_kill_g`). Resolves in `localization`.
   */
  NameID?: string;
  /**
   * Resolved display name (block 0 of NameID).
   */
  Name?: string;
  /**
   * Resolved description (block 1 of NameID).
   */
  Description?: string;
  /**
   * Every `TextBlocks.GetString` key referenced in this directive property's source code. See `UpgradeDProperty.LocalizationKeys` for details.
   */
  LocalizationKeys?: string[];
  /**
   * Unity-serialized config for the directive property. Fields vary per subclass — for example DirectiveProperty_KillDeaths carries {kills: {min, max}, overtime, minThreatLevel, percentLostOnDeath}.
   */
  Raw?: {
    [k: string]: unknown;
  };
}
/**
 * A mission definition from Global.Instance.Missions. The base Mission class carries the headline metadata; concrete subclasses (16 observed: AmalgamationMission, CleanupDetailMission, FlatTundraMission, SatelliteSalvageMission, …) add objective-specific fields that aren't dumped here individually.
 */
export interface MissionEntry {
  /**
   * Stable mission ID (matches the parent map's key).
   */
  ID: string;
  /**
   * Public Name property — usually the localized display name.
   */
  Name?: string;
  /**
   * Internal _missionName field — the canonical short ID (e.g. "sat_salvage", "ouroboros").
   */
  MissionName?: string;
  /**
   * Public TypeName property — display label for the mission type.
   */
  TypeName?: string;
  /**
   * Internal _missionTypeName field — same data via the field path.
   */
  MissionTypeName?: string;
  /**
   * Localized description; may be empty for auto-generated missions.
   */
  Description?: string;
  /**
   * C# class name of the concrete Mission subclass.
   */
  Subclass: string;
  /**
   * MissionType enum stringified (e.g. "None", "CleanupDetail", "Amalgamation").
   */
  MissionType?: string;
  /**
   * MissionFlags flag-enum stringified (comma-separated, e.g. "NormalMission, CanJoinDuringMission, AllowAsLobbyFilter").
   */
  MissionFlags?: string;
  /**
   * LevelFlags flag-enum stringified — which world regions can host this mission.
   */
  CompatibleLevels?: string;
  ShowHeader?: boolean;
  DisableWithoutCommand?: boolean;
  /**
   * Whether the mission can be selected via the mission picker.
   */
  Selectable?: boolean;
  ShowInReplayMenu?: boolean;
  AutoStart?: boolean;
  StartFirstObjective?: boolean;
  /**
   * Whether the mission ends with an extraction sequence.
   */
  ExtractAtEnd?: boolean;
  /**
   * Whether the mission resets weekly (for recurring rewards).
   */
  ResetWeekly?: boolean;
  /**
   * If true, the mission ignores the default reward table and only grants AdditionalRewards.
   */
  DisableDefaultRewards?: boolean;
  ShowButDontGiveAdditionalRewards?: boolean;
  PlayStartVoicelineOnLateJoin?: boolean;
  /**
   * Stable index within the missions list.
   */
  Index?: number;
  /**
   * Minimum intensity tier required to play.
   */
  MinIntensity?: number;
  /**
   * Minimum player level required.
   */
  MinLevelToStart?: number;
  OverrideExtractDuration?: number;
  /**
   * Multiplier on team revives (0 disables, negative values are special-case sentinel values for some missions).
   */
  TeamReviveMultiplier?: number;
  ExpectedDurationMultiplier?: number;
  MissionXPMultiplier?: number;
  MissionScriptMultiplier?: number;
  PlayStartVoicelineDuringDropDelay?: number;
  /**
   * Theme color as Unity RGBA(r, g, b, a) string.
   */
  Color?: string;
  Icon?: DIcon;
  /**
   * Mission-start voiceline reference.
   */
  StartVoiceline?: {
    /**
     * TextBlocks key (also routes the Wwise event).
     */
    ID?: string;
    /**
     * Resolved intro line from TextBlocks block 0.
     */
    Text?: string;
    Priority?: number;
  };
  /**
   * Scenes this mission can run in.
   */
  ValidScenes?: SceneRef[];
  /**
   * One-off rewards granted on completion (LevelUnlockEntry list).
   */
  AdditionalRewards?: LevelUnlockEntry[];
  /**
   * Rewards granted on repeat completions (LevelUnlockEntry list).
   */
  RepeatRewards?: LevelUnlockEntry[];
  /**
   * Full Mission ScriptableObject serialized via Unity JsonUtility. Captures every subclass-specific [SerializeField] field — e.g. AmalgamationMission.region/scene/globalEvent/hardModeModifierCount, CleanupDetailMission.cleanupDetailObjective/trailCount/bossObjective/bossVoiceline, SatelliteSalvageMission.powerDecommissionersObjective/alignDecommissionersObjective/satelliteObjective/decommissionerCount/powerLineCount, SaxoniteExcavationMission.corroderObjective/purgeObjective/prospectingCount, etc. Object references appear as {"instanceID":N,"@ref":"<type>:<key>"} pairs so consumers can resolve them against the catalog (objectives/regions/missionModifiers/globalEvents/lootPools).
   */
  RawData?: {};
}
/**
 * Reference to a Unity scene with its localization key.
 */
export interface SceneRef {
  /**
   * Unity scene asset name.
   */
  Scene?: string;
  /**
   * Localization key for the location's display name.
   */
  LocationName?: string;
}
/**
 * An objective prefab (NetworkBehaviour deriving from ObjectiveBase). Missions reference these through serialized fields — e.g. CleanupDetailMission.cleanupDetailObjective points here. Discovered via Resources.FindObjectsOfTypeAll<ObjectiveBase>(). 35 prefabs observed across 33 unique subclasses (EnemyWaveObjective is reused for Abomination/GenericGunk; EradicateObjective likewise).
 */
export interface ObjectiveEntry {
  /**
   * gameObject.name of the prefab — doubles as the @ref key ("objective:<Name>").
   */
  Name: string;
  /**
   * C# class name of the concrete ObjectiveBase subclass ("AmalgamationObjective", "ExtractObjective", "PowerTargetsObjective", …).
   */
  Subclass: string;
  /**
   * Public Title property (TextBlocks-resolved when localized).
   */
  Title?: string;
  /**
   * Whether the objective contributes a waypoint ping on activation.
   */
  AddWaypoint?: boolean;
  /**
   * Whether MoveNext() runs on Activate() to populate the HUD immediately.
   */
  SetupUIOnActivate?: boolean;
  ShowCompleteMessage?: boolean;
  /**
   * True if the prefab implements ISideObjective.
   */
  IsSideObjective?: boolean;
  /**
   * Voiceline played when the objective activates.
   */
  StartVoiceline?: {
    /**
     * TextBlocks key (also routes the Wwise event).
     */
    ID?: string;
    /**
     * Resolved line from TextBlocks block 0.
     */
    Text?: string;
    Priority?: number;
  };
  /**
   * Voiceline played when the objective completes successfully.
   */
  CompleteVoiceline?: {
    /**
     * TextBlocks key.
     */
    ID?: string;
    /**
     * Resolved line.
     */
    Text?: string;
    Priority?: number;
  };
  /**
   * Per-step HUD strings shown sequentially as the objective progresses through its phases. Each step has a localization key + resolved title/description, and a flag controlling whether numerical progress is rendered.
   */
  ObjectiveInfoList?: {
    /**
     * TextBlocks key for the step title (e.g. "o_breach").
     */
    TitleID?: string;
    /**
     * Resolved title (e.g. "Breach The Door").
     */
    Title?: string;
    /**
     * TextBlocks key for the step description.
     */
    DescriptionID?: string;
    /**
     * Resolved description.
     */
    Description?: string;
    ShowNumberProgress?: boolean;
  }[];
  /**
   * Full prefab serialized via JsonUtility — captures every [SerializeField] on the concrete subclass (decommissioner/relay/sub-objective references, scene refs, target counts, sub-event prefabs). Object references include the {"instanceID":N,"@ref":"<type>:<key>"} sibling for resolution.
   */
  RawData?: {};
}
/**
 * A world region — a thematic grouping of scenes (e.g. "Tundra", "Desert", "Gravity Farms"). 5 entries.
 */
export interface Region {
  /**
   * Stable region ID (also used stringified as the parent map's key).
   */
  ID: number;
  /**
   * Internal short ID (e.g. "tundra", "desert", "gravityfarm", "city", "icefloes").
   */
  NameID: string;
  /**
   * Localized display name.
   */
  RegionName?: string;
  /**
   * Localized display name with rich-text color tags.
   */
  ColoredRegionName?: string;
  LocalizedDescription?: string;
  /**
   * LevelFlags flag-enum stringified (e.g. "SpawnCombatResource, SpawnParkourResource, GravityFarm").
   */
  Flags?: string;
  /**
   * Theme color as Unity RGBA(r, g, b, a) string.
   */
  Color?: string;
  LockRegion?: boolean;
  Icon?: DIcon;
  /**
   * Scenes belonging to this region.
   */
  Scenes?: SceneRef[];
}
/**
 * An EnemyClass entry — a recipe for spawning a particular enemy archetype, with its body parts, behavior config, and tag flags.
 */
export interface Enemy {
  /**
   * EnemyClass.ID (stringified).
   */
  ID: string;
  /**
   * Public Name property (display).
   */
  Name?: string;
  /**
   * Stable API name.
   */
  APIName?: string;
  /**
   * Internal `_name` field — short identifier used in code (e.g. "b_lasercopter", "Slicer").
   */
  InternalName: string;
  /**
   * EnemyTags flag-enum stringified, comma-separated. Known values: Gunner, Flyer, Exploder, Sniper, Shielder, Support, Turret, Tall, Crawler, Difficult, Immunity, Oxythane.
   */
  Tags?: string;
  /**
   * LevelFlags flag-enum stringified — which world regions this enemy can spawn in.
   */
  LevelFlags?: string;
  /**
   * Replaces the default upgrade drop chance for this enemy (-1 = use default).
   */
  OverrideUpgradeDropChance?: number;
  /**
   * Probability the enemy spawns overclocked (0..1).
   */
  OverclockChance?: number;
  /**
   * Multiplier applied to outer-shell health relative to core health.
   */
  ShellHealthMultiplier?: number;
  CanBeDespawned?: boolean;
  /**
   * Minimum number of legs spawned with this enemy.
   */
  MinLegs?: number;
  /**
   * Maximum number of legs.
   */
  MaxLegs?: number;
  /**
   * Probability of spawning arms (0..1).
   */
  ArmChance?: number;
  /**
   * Probability of spawning legs at all (0..1).
   */
  LegChance?: number;
  Config?: EnemyConfig;
  /**
   * Extra rewards fired when this enemy is killed (LevelUnlockList from EnemyClass.CustomLoot). Same shape as gear LevelUnlocks. Most enemies have nothing here; bosses (e.g. Amalgamation) and special enemies (Pillabom, Missilehead) have entries.
   */
  CustomLoot?: LevelUnlockEntry[];
}
/**
 * Per-enemy behavior tuning — the bulk of the calculator-relevant fields. Mirrors EnemyBrain+Config.
 */
export interface EnemyConfig {
  /**
   * EnemyType enum stringified (e.g. "Grunt", "Brute", "Abomination").
   */
  EnemyType?: string;
  /**
   * Number of "enemy slots" this enemy occupies in spawn budgets (overrides type default if set).
   */
  OverrideEnemySlots?: number;
  /**
   * NavMesh agent type — controls which surfaces the enemy can traverse.
   */
  AgentSize?: number;
  /**
   * Pathfinding radius in units.
   */
  NavRadius?: number;
  /**
   * If true, the core mesh is not randomly rotated on spawn.
   */
  DontRandRotateCore?: boolean;
  MaxFlankTime?: number;
  MinFlankDistance?: number;
  TryFlankTime?: number;
  /**
   * Probability the enemy attempts to flank (0..1).
   */
  FlankChance?: number;
  /**
   * Base movement speed in units/second.
   */
  MoveSpeed?: number;
  RigidbodySpeedMultiplier?: number;
  /**
   * Turn rate in degrees/second.
   */
  TurnSpeed?: number;
  OverrideAcceleration?: number;
  OverrideStoppingDistance?: number;
  AllowRigidbodyMovement?: boolean;
  BalanceDurationBeforeDisablingRigidbodyMovement?: number;
  /**
   * Minimum legs required for the enemy to remain balanced before ragdolling.
   */
  MinLegsToBalance?: number;
  /**
   * Force in Newtons (-ish) required to topple the enemy.
   */
  RagdollForceThreshold?: number;
  /**
   * Probability of entering hit-stun on damage (0..1).
   */
  HitStunChance?: number;
  AddedHeight?: number;
  DisableNavigation?: boolean;
  NavPriority?: number;
  DontDespawnWhenUnableToPath?: boolean;
  DontLowerTowardTargetWhenFlying?: boolean;
  OverrideThrusterHoverHeight?: number;
  CanAttackMultipleTargets?: boolean;
  MaxConcurrentMeleeAttacks?: number;
  /**
   * Cooldown between melee swings in seconds.
   */
  MeleeInterval?: number;
  /**
   * Cooldown between target re-evaluations in seconds.
   */
  SwitchTargetInterval?: number;
  /**
   * Probability of switching target each evaluation tick (0..1).
   */
  SwitchTargetChance?: number;
  /**
   * Range at which the enemy seeks regrowable body parts.
   */
  LookForPartDistance?: number;
  LookForPartInterval?: number;
  /**
   * Cooldown before a destroyed limb can regrow.
   */
  RegrowLimbCooldown?: number;
  /**
   * Time to fully regrow a limb.
   */
  RegrowLimbDuration?: number;
  OnlyUseCoreHealthForHealthbar?: boolean;
}
/**
 * A status-effect element (e.g. Fire, Acid, Decay, Electric). Combat math like DPS and tick rate is implemented in code rather than declared here; this object holds the identity, theming, and stage count.
 */
export interface StatusEffect {
  /**
   * Internal effectID (e.g. "el_acid", "el_decay", "el_fire").
   */
  ID: string;
  /**
   * Display name ("Acid", "Decay").
   */
  Name?: string;
  /**
   * Display name wrapped in a rich-text color tag.
   */
  ColoredName?: string;
  /**
   * Active verb (e.g. "Corrode", "Burn", "Decay").
   */
  VerbName?: string;
  /**
   * Past-tense verb (e.g. "Corroded").
   */
  PastVerbName?: string;
  /**
   * Inline rich-text sprite tag for embedding the effect icon in tooltips.
   */
  IconTextTag?: string;
  /**
   * Whether targets affected by this status cannot regenerate health.
   */
  StopsHealthRegeneration?: boolean;
  /**
   * Stage threshold (0..1) at which the effect counts as "applied".
   */
  MinStageValue?: number;
  /**
   * Wwise switch ID used to route audio for this element.
   */
  ElementSwitchID?: number;
  /**
   * Number of intensity stages defined (`stages` array length).
   */
  NumStages?: number;
  TrailColor?: string;
  LaserColor?: string;
  TextColor?: string;
  IconColor?: string;
  MuzzleFlashColor?: string;
  Icon?: DIcon;
  /**
   * Decompilation-derived per-effect combat tuning. Values are `const`/inlined in C# subclasses, not runtime-readable as instance fields. Default behavior is `DamageMultiplier=1`, `FullSaturationLifetime=3s`, `DecayDelay=3s`, `DecaySpeed=0.3/s` — overrides are noted per element.
   */
  Tuning?: {
    /**
     * Applied to non-self damage when the effect is fully saturated. 1.0 default; 1.2 for Decay, 1.35 for Rot (metal targets only). Other effects are 1.0.
     */
    DamageMultiplier?: number;
    /**
     * Seconds the saturation persists after reaching full. 3 (default), 4 (Decay), 4.5 (Water), 5 (Bee), 60 (Rot), 1.6 player / 0.6 enemy (Immunity), 30 EnemyCore / 5 other (YellowResource).
     */
    FullSaturationLifetime?: number;
    /**
     * Seconds after last application before saturation begins decaying. 3 default; 0.5 for Immunity.
     */
    DecayDelay?: number;
    /**
     * Saturation decay rate. 0.3 / s default; 20 / s for Immunity (effectively instant).
     */
    DecaySpeed?: number;
  };
}
/**
 * A stacking modifier (PlayerStackData) — describes how a buff/debuff or counter stacks on the player.
 */
export interface Stack {
  /**
   * Internal stack identifier (e.g. "scrap", "wildfire", "dmr_boost").
   */
  Name: string;
  /**
   * Theme color.
   */
  Color?: string;
  /**
   * Maximum number of stacks.
   */
  MaxStacks?: number;
  /**
   * Seconds between losing one stack (0 = no periodic decay).
   */
  LoseStackInterval?: number;
  /**
   * Seconds after which all stacks expire (0 = no timeout).
   */
  TimeOutDuration?: number;
  TimeoutOnLevelLoad?: boolean;
  DisplayOnHUD?: boolean;
  Icon?: DIcon;
}
/**
 * A threat tier (ThreatData) — controls mission difficulty and per-tier reward pools. "threat1" is easiest, "threat7" hardest.
 */
export interface Threat {
  /**
   * Internal threat name ("threat1".. "threat7").
   */
  ID: string;
  /**
   * Display name ("Safe", "Brutal", …).
   */
  Name?: string;
  /**
   * Numbered label (e.g. "Threat Level 1").
   */
  NumberLabel?: string;
  Color?: string;
  Icon?: DIcon;
  /**
   * Rewards granted on mission completion at this threat tier. Same shape as gear LevelUnlocks.
   */
  MissionRewards?: LevelUnlockEntry[];
}
/**
 * A mission modifier (e.g. "Horde", "Fog", "Mortar Spawns"). Each MissionContainer's weekly rotation pulls a small set of these to alter mission behavior.
 */
export interface MissionModifier {
  /**
   * Stable modifier ID (also used stringified as the parent map's key).
   */
  ID: number;
  /**
   * Internal name (e.g. "m_horde", "m_fog", "m_mortar").
   */
  ModifierName: string;
  APIName?: string;
  /**
   * Localized display name.
   */
  Name?: string;
  /**
   * Localized description.
   */
  Description?: string;
  /**
   * Combined rich-text title + description as shown in the modifier popup.
   */
  TitleAndDescription?: string;
  /**
   * C# class name. Most are "MissionModifierGeneric"; some are wave-specific ("MissionModifierWaveModifier") or named subclasses ("MissionModifierHorde").
   */
  Subclass?: string;
  /**
   * ModifierFlags flag-enum stringified (e.g. "AllowInNormalMissions").
   */
  Flags?: string;
  /**
   * Danger enum stringified ("None", "Low", "Medium", "High", "Extreme").
   */
  Danger?: string;
  /**
   * Whether multiple instances of this modifier can apply at once.
   */
  CanStack?: boolean;
  /**
   * XP bonus when this modifier is active (e.g. 1.3 = +30%).
   */
  XPMultiplier?: number;
  Color?: string;
  TextColor?: string;
  Icon?: DIcon;
  /**
   * Mission IDs this modifier is incompatible with (matching keys in the missions map).
   */
  IncompatibleMissions?: string[];
  /**
   * Modifier IDs this modifier is incompatible with.
   */
  IncompatibleModifiers?: number[];
}
/**
 * A weighted pool of upgrade keys. Drawing one upgrade at random uses `Weight` as the probability mass (sum-normalized).
 */
export interface LootPool {
  /**
   * Pool name (matches the parent map's key).
   */
  Name: string;
  Upgrades?: {
    /**
     * Upgrade key (matches a key in the top-level `upgrades` map).
     */
    Upgrade: string;
    /**
     * Relative weight; not normalized. Higher value = more likely.
     */
    Weight: number;
  }[];
}
/**
 * One entry from `TextBlocks.strings`. The first block is the canonical text the game shows when calling `TextBlocks.GetString(key)`. For upgrade keys, block [0] is the Name and block [1] is the Description.
 */
export interface Localization {
  /**
   * Stable numeric ID assigned to this group during CSV import.
   */
  ID?: number;
  /**
   * One or more text variants. `TextBlocks.GetString(key)` returns `Blocks[0].Text` by default.
   */
  Blocks: {
    /**
     * The displayed text (may include rich-text tags).
     */
    Text?: string;
    /**
     * Optional stamp from the source CSV.
     */
    UniqueID?: string;
  }[];
}
/**
 * Singleton dump of the player MonoBehaviour prefab. Holds every base movement/health/wallrun/slide/clamber/jump/gravity/acceleration parameter. One entry — the player rig is shared across all four characters; per-character variation comes from upgrades and skill tree, not from this base.
 */
export interface PlayerBase {
  Name?: string;
  /**
   * Full Unity-serialized prefab data. Key fields: `moveSpeed`, `walkSpeed`, `crouchSpeed`, `jumpSpeed`, `airJumps`, `slideSpeed`, `wallrunSpeedAcceleration`, `wallrunDuration`, `wallrunYSpeedIntensity`, `gravityMultiplier`, `fallVelocityDrag`, `maxHealth`, `healthRegenTarget`, plus all the acceleration/deceleration/coyote-time parameters.
   */
  RawData?: {};
}
/**
 * An AuthItem (redemption-code inventory item).
 */
export interface AuthItem {
  ID: string;
  Name?: string;
  Color?: string;
  Rarity?: "Standard" | "Rare" | "Epic" | "Exotic";
  /**
   * Character APIName (matches `characters` map key).
   */
  Character?: string;
  /**
   * Upgrade key (matches `upgrades` map key).
   */
  Upgrade?: string;
}
/**
 * A special hex-grid pattern. When the player's upgrade grid layout matches the pattern, the rewards fire.
 */
export interface PatternPath {
  ID: number;
  /**
   * ScriptableObject asset name.
   */
  Name?: string;
  /**
   * RarityFlags enum stringified — which upgrade rarities count toward this pattern ("None" means any).
   */
  Rarities?: string;
  Pattern?: HexMap;
  Rewards?: LevelUnlockEntry[];
}
/**
 * A `ThreatModifier<float>` — array indexed by threat tier (index 0 = threat1, index 6 = threat7).
 */
export interface ThreatProfile {
  Name: string;
  /**
   * @minItems 7
   * @maxItems 7
   */
  Threats: [number, number, number, number, number, number, number];
}
/**
 * A wave-composition spec used by the enemy spawn system.
 */
export interface CustomWave {
  Name: string;
  /**
   * Concrete CustomWave subclass (e.g. GenericCustomWave).
   */
  Subclass: string;
  /**
   * EnemyTags flag-enum stringified — included tags.
   */
  Tags?: string;
  ExcludeTags?: string;
  /**
   * EnemyTypeFlags flag-enum stringified.
   */
  Types?: string;
  EnemyCountMultiplier?: number;
  OverclockChanceMultiplier?: number;
  /**
   * ComponentSize enum ("Small", "Medium", "Large").
   */
  MinRoomSize?: string;
  /**
   * Minimum Ouroboros rooms required for this wave to spawn (-1 = no constraint).
   */
  MinOuroRooms?: number;
  TagChances?: {
    Tag?: string;
    Multiplier?: number;
  }[];
  TypeChances?: {
    Type?: string;
    Multiplier?: number;
  }[];
  AddAttachments?: boolean;
  OverrideIndividualEnemies?: number;
}
/**
 * A world-collectable definition. The player gathers `Count` instances to fully claim the rewards.
 */
export interface Collectable {
  ID: string;
  Name?: string;
  Color?: string;
  Count?: number;
  /**
   * Localization key for the on-punch flavor line.
   */
  PunchTextID?: string;
  /**
   * Resolved flavor text from `PunchTextID` block 0.
   */
  PunchText?: string;
  Icon?: DIcon;
  Rewards?: LevelUnlockEntry[];
}
/**
 * A weighted bag of `EnemyClass` IDs grouped by an `EnemyType`. Used to vary enemy mix within a single type.
 */
export interface EnemyGroup {
  Name: string;
  EnemyType?: string;
  Enemies?: {
    /**
     * Enemy ID (matches `enemies` map key).
     */
    Enemy: string;
    Weight: number;
  }[];
}
/**
 * A timed/seasonal global event — Amalgamation Hunt, Corp Contest, etc. Player-collective progress against `TotalRequiredProgress` triggers `Rewards` and optionally unlocks `EndMission`. Subclasses (AmalgamationGlobalEvent, CorpContestGlobalEvent) add subclass-specific tunables in `RawData`.
 */
export interface GlobalEvent {
  ID: string;
  /**
   * Concrete C# class name.
   */
  Subclass: string;
  EventID?: string;
  StatID?: string;
  Title?: string;
  Color?: string;
  Deactivate?: boolean;
  AreStatsRelative?: boolean;
  Completed?: boolean;
  CompleteOnFullProgress?: boolean;
  MustParticipateToClaimRewards?: boolean;
  PreviewEndMission?: boolean;
  /**
   * Unix timestamp (0 = no deadline). Real seasonal events have a non-zero value here.
   */
  EndDate?: number;
  TotalRequiredProgress?: number;
  ProgressOnMissionCompleted?: number;
  ProgressOnMissionCompletedVisualMultiplier?: number;
  ProgressDisplayMultiplier?: number;
  /**
   * Mission ID cross-ref (matches `missions` map key).
   */
  EndMission?: string;
  /**
   * MissionContainer asset name.
   */
  EndMissionContainer?: string;
  /**
   * Voiceline ID played when the event begins.
   */
  OnStartRoachardLine?: string;
  OnStartTextLog?: string;
  OnEndTextLog?: string;
  /**
   * Per-stat progress contributions tracked toward TotalRequiredProgress.
   */
  ProgressStats?: {
    /**
     * Localization key for the stat's display name.
     */
    TitleID?: string;
    /**
     * Steam stat / internal stat ID. May be empty (falls back to GlobalEvent.StatID).
     */
    StatID?: string;
    Color?: string;
    /**
     * ProgressDisplayType enum stringified.
     */
    DisplayType?: string;
  }[];
  /**
   * Rewards on completion (LevelUnlockEntry list).
   */
  Rewards?: LevelUnlockEntry[];
  /**
   * Full Unity-serialized event data. Subclass-specific fields (e.g. AmalgamationGlobalEvent's `missionModifier`, `modifierChance`, `maxInstanceDamage`, `maxDamageThreatMultiplier`, `HornetSwarmer`, `HornetCount`) live here. Catalog cross-references get `@ref` enrichment.
   */
  RawData?: {};
}
/**
 * A non-grid player upgrade.
 */
export interface PlayerUpgradeEntry {
  /**
   * ScriptableObject asset name.
   */
  Name: string;
  /**
   * Concrete C# class name (e.g. AirDashUpgrade, NoseDiveUpgrade, JetpackUpgrade, BlinkUpgrade, AimWhileSlidingUpgrade, SetFlagsPlayerUpgrade).
   */
  Subclass: string;
  /**
   * Character APIName whose `DefaultUpgrade` references this entry, if any. Null for skill-tree upgrades not bound to a specific character via DefaultUpgrade.
   */
  Character?: string;
  /**
   * Full Unity-serialized prefab data. Movement abilities (AirDash/NoseDive/Jetpack) include nested `Data` structs with all timing/force/duration tunables (e.g. `prefabData.leapForce`, `prefabData.maxFlyTime`, `prefabData.flyAngleBounds`, `prefabData.landDamageRadius`, etc.) plus `Cooldown` (rechargeDuration, maxCharges). Catalog cross-references inside RawData get `@ref` enrichment.
   */
  RawData?: {
    [k: string]: unknown;
  };
}
/**
 * Shared status-effect tuning constants (compile-time inlined in `StatusEffect.cs`).
 */
export interface StatusEffectGlobals {
  /**
   * Converts `damageEffectAmount` to saturation gain per hit (effectively /10).
   */
  SaturationAddMultiplier?: number;
  /**
   * Damage dealt when an effect first reaches full saturation, against enemy targets.
   */
  FullSaturationDamage?: number;
  /**
   * Damage-per-tick when a status effect is fully saturated against a player target.
   */
  PlayerDamageOnTick?: number;
  /**
   * AoE explosion damage multiplier on enemies (from on-saturation explosions).
   */
  ExplosionDamage?: number;
  /**
   * AoE explosion damage multiplier on players.
   */
  ExplosionPlayerDamage?: number;
  /**
   * Flat multiplier on damage with `DamageFlags.Explosive` set (`ITarget.ExplosiveDamageMultiplier`).
   */
  ExplosiveDamageMultiplier?: number;
}
/**
 * Hardcoded progression formulas (XP curves) extracted from decompiled source — not runtime-readable as data fields.
 */
export interface Formulas {
  /**
   * Each curve produces `coefficient * (currentLevel - LevelOffset + 1)^power + add`. Pick the curve whose `Context` matches the level bracket: `character_1_to_10` for character levels 1..10, `character_11_plus` for 11+, `gear_1_to_5` for gear levels 1..5, `gear_6_plus` for 6+.
   */
  XPCurves?: {
    Context: string;
    Description?: string;
    LevelOffset?: number;
    Coefficient: number;
    Power: number;
    Add: number;
  }[];
}
/**
 * Per-rarity pricing/visual. Sourced from the RarityData struct array on Global.Instance.Rarities (not a ScriptableObject — fields are reflectively read).
 */
export interface RarityEntry {
  /**
   * Canonical rarity key ("standard", "rare", "epic", "exotic", "contraband", "oddity").
   */
  Name: string;
  /**
   * Localization key for the display name.
   */
  LocalizedName?: string;
  /**
   * Rich-text color tag prefix used when this rarity's name is rendered inline.
   */
  ColorTag?: string;
  /**
   * Localization key for the "Boosted" variant label.
   */
  BoostedName?: string;
  /**
   * Localization key for the "Turbocharged" variant label.
   */
  TurbochargedName?: string;
  /**
   * Base scrip cost to unlock an upgrade at this rarity.
   */
  UpgradeScripCost?: number;
  /**
   * Base rare-resource cost.
   */
  UpgradeRareResourceCost?: number;
  /**
   * Ouroboros cleanse cost (paid in `ourosample`).
   */
  CleanseCost?: number;
  /**
   * Saxonite price for "craft new" rolls at this rarity.
   */
  CraftNewSaxoniteCost?: number;
  /**
   * Extra resources required beyond scrip+rare. Empty for most rarities.
   */
  AdditionalUpgradeCost?: DUnlockCost[];
  /**
   * PlayerResource ID (resolves in `resources`) — the scrap currency dismantling produces for this rarity.
   */
  ScrapResource?: string;
  /**
   * RGBA(r,g,b,a).
   */
  Color?: string;
  BackgroundColor?: string;
  LightColor?: string;
  Icon?: DIcon;
}
/**
 * Mission-container variant. The base class supplies AdditionalMissionFlags / RemovedMissionFlags; subclass-specific fields (e.g. WeeklyOvertimeAssignment.weekData[]) live in RawData.
 */
export interface MissionContainerEntry {
  /**
   * Asset name (also the parent map key).
   */
  Name: string;
  /**
   * C# class name.
   */
  Subclass: string;
  /**
   * Position in Global.Instance.MissionContainers.
   */
  Index?: number;
  /**
   * MissionFlags ORed onto every mission this container wraps.
   */
  AdditionalMissionFlags?: string;
  /**
   * MissionFlags ANDed off.
   */
  RemovedMissionFlags?: string;
  /**
   * Full SO via JsonUtility. WeeklyOvertimeAssignment includes `weekData[]` (start times, seeds, modifier instance IDs that resolve via @ref) plus `rewards` / `repeatableRewards` / `resetInterval` / `minThreat` / `minIntensity`.
   */
  RawData?: {};
}
/**
 * An entry from Global.Instance.encounters — a procedural-mission spawn rule (terrain feature, prop set, mini-objective). 20 entries.
 */
export interface EncounterEntry {
  /**
   * Asset name; also the @ref key (`encounter:<Name>`).
   */
  Name: string;
  /**
   * Concrete C# class name (CraterEncounter, PipelineEncounter, …).
   */
  Subclass: string;
  /**
   * Position in Global.Instance.encounters[].
   */
  Index?: number;
  /**
   * True for GameObject prefabs (component implements IEncounter); false for SO impls.
   */
  IsPrefab?: boolean;
  /**
   * Full encounter via JsonUtility. Per-subclass [SerializeField] fields — region masks, spawn weights, prefab refs, sub-objective targets. `null` for GameObject-prefab entries (5 of 20: Clear Objects Objective, LaptopRetrievalObjective, LostSaxitosEncounter, RelayTowers, UploadData SideObjective) since JsonUtility can't serialize a GameObject root — the encounter's `Name` doubles as the matching key in the `objectives` map for these.
   */
  RawData?: {} | null;
}
/**
 * Master quip/emote catalog entry. 63 entries spread across 4 characters.
 */
export interface QuipEntry {
  /**
   * Numeric quip ID (stable; the parent map key is this stringified).
   */
  ID: number;
  /**
   * Position in Global.Instance.Quips.
   */
  Index?: number;
  /**
   * _label — also doubles as the localization key.
   */
  Label: string;
  /**
   * CharacterType enum (Wrangler / Bruiser / Scrapper / Glider / All).
   */
  Character?: string;
  /**
   * QuipType flag-enum (None, Dance, DisableInVehicle).
   */
  QuipType?: string;
  /**
   * Localization key for the voiceline played when the quip fires (resolves in `localization`).
   */
  VoicelineTextID?: string;
  /**
   * Resolved text from `VoicelineTextID` block 0 — the actual line spoken.
   */
  VoicelineText?: string;
  TriggerOnFire?: boolean;
  CancelOnFire?: boolean;
  PlayThirdPersonAnimationForOwner?: boolean;
  HideThirdPersonWeapon?: boolean;
  IsThirdPersonAdditive?: boolean;
  MinAnimationInterval?: number;
  /**
   * Asset name of the first-person animation clip.
   */
  AnimationFirstPersonClip?: string;
  /**
   * Asset name of the third-person animation clip.
   */
  AnimationThirdPersonClip?: string;
  Icon?: DIcon;
}
/**
 * Master crafting price table. Singleton: there is exactly one `CraftingWindow` prefab in the game.
 */
export interface Crafting {
  /**
   * Player level required to access the crafting bench (10 in source).
   */
  MinLevelToAccessCrafting?: number;
  /**
   * Roll a fully-random new upgrade.
   */
  RandomCraftCost?: DUnlockCost[];
  /**
   * Roll a random upgrade for a specific gear.
   */
  WeaponCraftCost?: DUnlockCost[];
  /**
   * Duplicate an existing upgrade.
   */
  UpgradeCraftCost?: DUnlockCost[];
  /**
   * Tier-up: Standard → Rare.
   */
  UpcraftToRareCost?: DUnlockCost[];
  /**
   * Rare → Epic.
   */
  UpcraftToEpicCost?: DUnlockCost[];
  /**
   * Epic → Exotic.
   */
  UpcraftToExoticCost?: DUnlockCost[];
}
/**
 * Mission-control / crew dialogue system: the exchange catalog (id → trigger + lines + character refs) plus the per-trigger probability table.
 */
export interface DialogueData {
  /**
   * DialogueExchange catalog keyed by `id`.
   */
  Exchanges?: {
    [k: string]: DialogueEntry;
  };
  /**
   * Per-trigger probability indexed by `Mathf.Log2((int)Trigger)`. 12 entries: [None, Ambient, PlayerJoin, PlayerLeave, DropPodLaunch, DropPodFalling, DropPodLand, DropPodDoorOpen, DropPodReturnToHub, OpenInventory, Killed/KilledByPlayer, Revive].
   */
  TriggerChances?: number[];
}
/**
 * A scripted multi-line exchange between Mission Control and the crew.
 */
export interface DialogueEntry {
  /**
   * Localization key root — lines resolve via TextBlocks per-character variants.
   */
  ID: string;
  /**
   * Trigger enum stringified (Ambient / PlayerJoin / DropPodLaunch / Killed / Revive / …).
   */
  Trigger?: string;
  /**
   * MissionType flag-enum gating which mission types this exchange can play in.
   */
  MissionTypes?: string;
  /**
   * LevelFlags: Hub / NormalLevels / SpecialLevels.
   */
  LevelTypes?: string;
  /**
   * LevelFlags region mask.
   */
  ValidRegions?: string;
  /**
   * Dude asset name driving the exchange.
   */
  MainCharacter?: string;
  SecondaryCharacter?: string;
  Lines?: {
    /**
     * Dude asset name speaking this line.
     */
    Character?: string;
    /**
     * Seconds to wait before playing.
     */
    Delay?: number;
    /**
     * If true, plays simultaneously with the previous line.
     */
    StartWithNext?: boolean;
    /**
     * Resolved line text (block at line index N under the exchange's TextBlocks key).
     */
    Text?: string;
  }[];
}
/**
 * A named bundle of `UpgradeProperty` overrides referenced by `SkinUpgradeProperty_Preset.preset`. When a preset's parent `chance` roll succeeds, its inner `properties` list is applied on top of the parent skin (substituting one slot via `RandomContainerRange`).
 */
export interface UpgradePresetEntry {
  /**
   * SO asset name. Matches the parent map's key.
   */
  Name: string;
  /**
   * Suffix applied to a parent skin's display name when this preset rolls (e.g. "Coppertone" → "Factory (Coppertone)"). TextBlocks-resolved at runtime.
   */
  OverrideNameModifier?: string;
  /**
   * Hex color tag the modifier name is wrapped in (e.g. `f40857`).
   */
  NameModifierColor?: string;
  ShowNameInStats?: boolean;
  /**
   * Inclusive lower bound for the index-substitution roll inside the preset's property list. When `min == max`, no substitution happens; otherwise one entry in `[min, max]` replaces the entry at `min`.
   */
  RandomContainerRangeMin?: number;
  RandomContainerRangeMax?: number;
  /**
   * Resolved per-property summary of the preset's own `UpgradePropertyList`. Same shape as `Skin.Modifiers` — answers "what does this preset do?" without parsing `RawData`.
   */
  Modifiers?: DSkinModifier[];
  /**
   * Full `UpgradePreset` ScriptableObject serialized via Unity `JsonUtility`. Captures the inner `properties: UpgradePropertyList` (each entry an `UpgradeProperty` subclass — colors, trim refs, texture overrides — same shape as per-skin properties).
   */
  RawData?: {};
}
